# Generated by Django 4.2.21 on 2025-06-02 07:06

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='click_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shorturl',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shorturl',
            name='expire_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 3, 7, 6, 24, 335648, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
