# Generated by Django 4.2.21 on 2025-06-04 11:37

from django.db import migrations, models
import django.db.models.deletion
import shortener.models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_shorturl_click_count_shorturl_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shorturl',
            name='click_count',
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='expire_at',
            field=models.DateTimeField(default=shortener.models.default_expire_at),
        ),
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('short_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='shortener.shorturl')),
            ],
        ),
    ]
